###################################
#Troll Program By Jerry Huang lolol
#TROLOLOL

from graphics import *

def main():
    print("Welcome to the POWER OF SHIVUM GAME")
    print("-----------------------------------")
    name = input("You are taking a walk, when suddenly, you see a shiv midget. Who do you yell to for help? ")
    print("The", name, "midget comes, but is high on 420 blaze it, and is very drunk.")
    input("Press Enter to see what the midget looks like")

    #midget graph window
    midget = GraphWin("THE MIDGET", 400,400)
    face = Circle(Point(200,200), 100)
    face.setFill('dark red')
    leftCornea = Circle(Point(140,100), 15)
    leftCornea.setFill("blue")
    leftEye = Circle(Point(140, 100), 25)
    leftEye.setFill("white")
    rightCornea = leftCornea.clone()
    rightCornea.move(120,0)
    rightEye = leftEye.clone()
    rightEye.move(120,0)
    face.draw(midget)
    leftEye.draw(midget)
    leftCornea.draw(midget)
    rightEye.draw(midget)
    rightCornea.draw(midget)
    mouth = Rectangle(Point(70,150),Point(130,170))
    mouth.draw(midget)
    mouth.setFill("white")
    midget_talks = Text(Point(200,50), "Daaaaa I'm sooo high");midget_talks.draw(midget)
    Text(Point(200,350), "< Click anywhere to continue >").draw(midget)
    midget.getMouse()
    midget_talks.setText("Oh nooo da bic boi shivum is over there fuckk")
    midget.getMouse()
    midget.close()

    #shiv graph window
    shiv = GraphWin("THE POWER OF SHIVUM",400,400)
    face = Circle(Point(200,200), 100)
    face.setFill('saddlebrown')
    leftCornea = Circle(Point(140,170), 15)
    leftCornea.setFill("brown")
    leftEye = Circle(Point(140, 170), 25)
    leftEye.setFill("white")
    rightCornea = leftCornea.clone()
    rightCornea.move(120,0)
    rightEye = leftEye.clone()
    rightEye.move(120,0)
    face.draw(shiv)
    leftEye.draw(shiv)
    leftCornea.draw(shiv)
    rightEye.draw(shiv)
    rightCornea.draw(shiv)
    mouth = Rectangle(Point(180,200),Point(220,220))
    mouth.draw(shiv)
    mouth.setFill("white")
    Text(Point(200,350), "< Click anywhere to continue >").draw(shiv)
    shiv_talks = Text(Point(200,50), "HAHA you can't escape from me ya little sheet");shiv_talks.draw(shiv)
    shiv.getMouse()
    shiv_talks.setText("Do you 1.) Choose to fight me or, 2.) Run away?")
    shiv_input = Entry(Point(350,50), 5)
    shiv_input.draw(shiv)
    shiv.getMouse()
    if shiv_input.getText() == "1":
        shiv_input.undraw()
        shiv_talks.setText("Okay biatch. fight me irl")
        for i in range(150):
            circle = Circle(Point(200,242.5),i)
            circle.setFill('black')
            circle.draw(shiv)
            circle.undraw()
        shiv_talks.setText("OHHH SHIT HE HAD DA 2 CHOPSTICKS!!")
        for i in range(150,-1,-1):
            circle = Circle(Point(200,242.5),i)
            circle.setFill('black')
            circle.draw(shiv)
            circle.undraw()
        
    elif shiv_input.getText() == "2":
        shiv_input.undraw()
        shiv_talks.setText("Ya PUSSY ASS BITCH")
        shiv.getMouse()
        shiv_talks.setText("GET BACK HERE")
        face = Circle(Point(200,200), 100)
        face.setFill('red')
        leftCornea = Circle(Point(150,170), 5)
        leftCornea.setFill("red")
        leftEye = Circle(Point(150, 170), 30)
        leftEye.setFill("white")
        rightCornea = leftCornea.clone()
        rightCornea.move(100,0)
        rightEye = leftEye.clone()
        rightEye.move(100,0)
        face.draw(shiv)
        leftEye.draw(shiv)
        leftCornea.draw(shiv)
        rightEye.draw(shiv)
        rightCornea.draw(shiv)
        mouth = Oval(Point(150,220),Point(250,265))
        mouth.draw(shiv)
        mouth_text = Text(Point(200,242.5), "YOU SHIT!!");mouth_text.draw(shiv)
        mouth.setFill("white")
        shiv.getMouse()
        shiv_talks.setText("I'M GONNA SHOVE TWO CURRY CHOPSTICKS UP YO ASS IF YOU DON'T COME BACK")
        shiv.getMouse()
        shiv.close()
    else:
        shiv_input.undraw()
        shiv_talks.setText("WOW YA RETARD CAN\'T EVEN TYPE RIGHT DID YOU LIKE EVEN GO TO PRESCHOOL DUMBASS HAHA")
        shiv.getMouse()
        shiv_talks.setText("Why don't you go kill yo self HAHA")
        face = Circle(Point(200,200), 100)
        face.setFill('saddlebrown')
        leftCornea = Circle(Point(140,170), 15)
        leftCornea.setFill("brown")
        leftEye = Circle(Point(140, 170), 25)
        leftEye.setFill("white")
        rightCornea = leftCornea.clone()
        rightCornea.move(120,0)
        rightEye = leftEye.clone()
        rightEye.move(120,0)
        face.draw(shiv)
        leftEye.draw(shiv)
        leftCornea.draw(shiv)
        rightEye.draw(shiv)
        rightCornea.draw(shiv)
        mouth = Rectangle(Point(180,200),Point(220,220))
        mouth.draw(shiv)
        mouth.setFill("white")
        shiv.getMouse()

main()
